resources:
  6_pose:
    read_topic: "machine_id_address/publish"
    unit: null
    write_topic: null
  device_info_address:
    read_topic: "device_info_address/publish"
    unit: null
    write_topic: null
  device_configuration_address:
    read_topic: "device_configuration_address/publish"
    unit: null
    write_topic: "device_configuration_address/command"
  transducer_ratio:
    read_topic: "transducer_ratio/publish"
    unit: null
    write_topic: "transducer_ratio/command"
  active_power_line_phase1_address:
    read_topic: "active_power_line_phase1_address/publish"
    unit: "W"
    write_topic: null
  active_power_line_phase2_address:
    read_topic: "active_power_line_phase2_address/publish"
    unit: "W"
    write_topic: null
  active_power_line_phase3_address:
    read_topic: "active_power_line_phase3_address/publish"
    unit: "W"
    write_topic: null
  reactive_power_line_phase1_address:
    read_topic: "reactive_power_line_phase1_address/publish"
    unit: "W"
    write_topic: null
  reactive_power_line_phase2_address:
    read_topic: "reactive_power_line_phase2_address/publish"
    unit: "W"
    write_topic: null
  reactive_power_line_phase3_address:
    read_topic: "reactive_power_line_phase3_address/publish"
    unit: "W"
    write_topic: null
  current_line1_address:
    read_topic: "current_line1_address/publish"
    unit: "A"
    write_topic: null
  current_line2_address:
    read_topic: "current_line2_address/publish"
    unit: "A"
    write_topic: null
  current_line3_address:
    read_topic: "current_line3_address/publish"
    unit: "A"
    write_topic: null
  voltage_l1_n_address:
    read_topic: "voltage_l1_n_address/publish"
    unit: "V"
    write_topic: null
  voltage_l2_n_address:
    read_topic: "voltage_l2_n_address/publish"
    unit: "V"
    write_topic: null
  voltage_l3_n_address:
    read_topic: "voltage_l3_n_address/publish"
    unit: "V"
    write_topic: null
  voltage_l1_l2_address:
    read_topic: "voltage_l1_l2_address/publish"
    unit: "V"
    write_topic: null
  voltage_l2_l3_address:
    read_topic: "voltage_l2_l3_address/publish"
    unit: "V"
    write_topic: null
  voltage_l3_l1_address:
    read_topic: "voltage_l3_l1_address/publish"
    unit: "V"
    write_topic: null