resources:
  daily_done_bags:
    uuid: "daily_done_bags"
    version: 1
    device: "Production"
    name: ["daily_done_bags"]
    unit: ["count"]
    topic: "production/cycle/signals/actual_done_bags/telemetry"
    qos: 2
    operation: 'sum'
    value: 0
  daily_placed_objects:
    uuid: "daily_placed_objects"
    version: 1
    device: "Production"
    name: ["daily_placed_objects"]
    unit: ["count"]
    topic: "production/cycle/signals/actual_placed_objects/telemetry"
    qos: 2
    operation: 'sum'
    value: 0
  cycle_time:
    uuid: "cycle_time"
    version: 1
    device: "Production"
    name: ["cycle_time"]
    unit: ["s"]
    topic: "production/cycle/time/telemetry"
    qos: 2
    operation: 'mean'
    value: 0
  object_type:
    uuid: "object_type"
    version: 1
    device: "Production"
    name: ["object_type"]
    unit: ["B"]
    topic: "production/cycle/signals/current_object/telemetry"
    qos: 0
    operation: 'assign'
    value: ''
  confidence:
    uuid: "confidence"
    version: 1
    device: "AIonEdge"
    name: ["score"]
    unit: ["%"]
    topic: "ai_on_edge/inference/scores/confidence/telemetry"
    qos: 2
    operation: 'double_mean'
    value: 0
  cosine_similarity:
    uuid: "cosine_similarity"
    version: 1
    device: "AIonEdge"
    name: ["score"]
    unit: ["%"]
    topic: "ai_on_edge/inference/scores/cosine_similarity/telemetry"
    qos: 2
    operation: 'double_mean'
    value: 0
  inference_time:
    uuid: "inference_time"
    version: 1
    device: "AIonEdge"
    name: ["inference_time"]
    unit: ["s"]
    topic: "ai_on_edge/inference/time/telemetry"
    qos: 2
    operation: 'mean'
    value: 0
  plc_daily_done_bags:
    uuid: "plc_daily_done_bags"
    version: 1
    device: "Conveyor"
    name: [ "plc_daily_done_bags" ]
    unit: [ "count" ]
    topic: "conveyor/states/cycle/actual_unloaded_objects/telemetry"
    qos: 2
    operation: 'sum'
    value: 0